# -*- coding: utf-8 -*-
"""IMU_assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pe3ixkVzutT41fPG_NwDxTElUN0Vnm0w
"""

# Create a simulation of an inertial measurement unit (IMU) moving in a 2D plane

# The goals are to compute and visualize:
# 1. The IMU position and orientation over time
# 2. the ideal accelerometer measurement in the IMU frame
# 3. Adhere to all the deliverables presented in the document
# 4. Make sure that all those tasks are completed both in the 2-D and 3-D space

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

from matplotlib.patches import FancyArrow
from matplotlib.gridspec import GridSpec

#-- 1. Simulation parameters ----------------------------

dt = 0.1 #so that is our delta t
T = 20.0 # total time
t = np.arange(0, T+dt, dt) # this would be our time array

# we need to create a shape for this as well
N = len(t)

f1, f2, f3, f4 = 1.0, 0.5, 0.75, 0.35 #defining our frequencies [Hz]

# define gravity
g_I = np.array([0.0, 9.81])  # now we have all the variables defined

# make the gravity in 3d as well

g_I_3d = np.array([0.0, 0.0, 9.81])  # this is our gravity in the 3D (z positive)

#-- 2. 2-D simulation -----------------------------------

# Assumptions:
# Theta(t) is the IMU orientation angle measured from the inertial frame

# Steps:
# Let's start with computing the iMU position (x(t), z(t))
# Let's start with creating a function for the 2-d simulation
def simulate_2d():

# we need to compute the IMU position and the orientation of theta(t)

  vx = 0.2*np.sin(2*np.pi*f1*t)
  vz = 0.5 *np.sin(2*np.pi*f2*t)
  wy = 0.5*(1.0+np.sin(2*np.pi*f3*t))

# We need to integrate the position of these (we are going to need this later)
  x = np.zeros(N)
  z = np.zeros(N)

# now we need to create a loop that will go through all our data and fill out
  for i in range(1,N):
      x[i] = x[i-1] + vx[i-1]*dt
      z[i] = z[i-1] + vz[i-1]*dt

# so after creating the loop we can integrate the IMU orientation of theta
  theta = np.zeros(N)
  for i in range(1,N):
    theta[i] = theta[i-1] + wy[i-1]*dt

# we need to do our acceleration and the derivative of the velocity

  ax_I = 0.2*2*np.pi*f1*np.cos(2*np.pi*f1*t)
  az_I = 0.5*2*np.pi*f2*np.cos(2*np.pi*f2*t)

# now we need to transform the body into inertial

  a = np.cos(theta) # cos of theta
  b = np.sin(theta) # our sin of theta

  net_ax = ax_I - g_I[0] #so when our g_I is 0
  net_az = az_I - g_I[1] #we subtract the g=9.81 and the z_I is in the positive direct.

  fx_b = a*net_ax + b*net_az    # our x direction
  fz_b = -b*net_ax + a*net_az   # our z direction


  return dict(t=t, x=x, z=z, theta=theta, vx=vx, vz=vz,
              ax_I=ax_I, az_I=az_I, fx_b=fx_b, fz_b=fz_b, wy=wy)

# -- 3. 3-D simulation and defining all the varibles before the modeling --------

# need to define all variables for the 3-D model simulation

def simulate_3d():
    vx = 0.2*np.sin(2*np.pi*f1*t)
    vy = 0.5 *np.sin(2*np.pi*f2*t)
    vz = 0.5 *np.sin(2*np.pi*f2*t)
    wx = 0.25*(1.0+np.sin(2*np.pi*f4*t))
    wy = 0.5*(1.0+np.sin(2*np.pi*f3*t))
    wz = np.zeros(N)

# you need to make sure that you have all the variables from the 3-d part
# so you can utulize them later while modeling

# you now need to create empty arrays that you are going to fill up while you are
# going through for loops

    x = np.zeros(N)
    y = np.zeros(N)
    z = np.zeros(N)

    for i in range(1, N):
        x[i] = x[i-1] + vx[i-1]*dt
        y[i] = y[i-1] + vy[i-1]*dt
        z[i] = z[i-1] + vz[i-1]*dt
# now we need to create a rotation matrix that will convert the vectors between
# the body and the inertial frame
    R = np.eye(3)
    Rs = np.zeros((N, 3, 3))
    Rs[0] = R.copy()
    for i in range(1,N):
        Omega = np.array([
                [0, -wz[i-1], wy[i-1]],   # NOTE: always make sure that your
                [wz[i-1], 0, -wx[i-1]],   # indentations are correct and everything
                [-wy[i-1], wx[i-1], 0]    # is set up correctly so that there is no error
                ])
        R = R @ (np.eye(3) + Omega*dt)
        U, _, Vt = np.linalg.svd(R)
        R = U @ Vt
        Rs[i] = R.copy()

# make sure that you utulize all the necessary functions and use the matrix math

    R = R@(np.eye(3)+Omega*dt)
    U, _, Vt = np.linalg.svd(R)
    R = U @ Vt
    Rs[i] = R.copy()

#you need to have all the components from the 2-D for teh 3-D stuff
    ax_I = 0.2*2*np.pi*f1*np.cos(2*np.pi*f1*t)
    ay_I = 0.5*2*np.pi*f2*np.cos(2*np.pi*f2*t)
    az_I = 0.5*2*np.pi*f2*np.cos(2*np.pi*f2*t)

    fx_b = np.zeros(N); fy_b = np.zeros(N); fz_b = np.zeros(N)

    for i in range(N):
        a_I = np.array([ax_I[i], ay_I[i], az_I[i]])
        f_B = Rs[i].T @ (a_I - g_I_3d)
        fx_b[i] = f_B[0]; fy_b[i] = f_B[1]; fz_b[i] = f_B[2]

# return all the parameters calculated correctly and return them so
# you can utulize them to create your own IUMs

    return dict(t=t, x=x, y=y, z=z, Rs=Rs,
                wx=wx, wy=wy, wz=wz,
                fx_b=fx_b, fy_b=fy_b, fz_b=fz_b)

# now we can move onto 2-D graphing of the data that was processed

#-- 4. Plotting in 2-D ------------------------------------

# Create a plot from the previous variables and create a plot that will
# showcase all the variables in a 2-D space

def plot_2d(d):
    fig, axes = plt.subplots(2, 2, figsize=(12, 8))
    fig.suptitle("2D IMU simulation exercise", fontsize=14)
    plt.tight_layout(pad=3.0)

# Create different subplots that will be responsible for graphing
# each section

# 1. We are graphing first the trajectory with x and z variables
    axes[0,0].plot(d['x'], d['z'])
    axes[0,0].set(title="IMU trajectory in the inertial frame",xlabel="x[m]",ylabel="z[m]")
    axes[0,0].grid(True)
    axes[0,0].invert_yaxis()

# 2. We are now graphing the orientation of theta with accurate labales
    axes[0,1].plot(d['t'], d['theta'])
    axes[0,1].set(title="IMU orientation along the trajectory", xlabel="time[s]", ylabel="theta[rad]")
    axes[0,1].grid(True)

# 3. The 3rd deliverable was to create a visualization of the IMU mostion in the
# plane so we are also plotting that with the usage of theta
    axes[1,0].plot(d['x'], d['z'], color='black', lw=1)
    axes[1,0].set(title="Visualization of the IMU motion in the plane", xlabel="x [m]", ylabel="z [m]")
    axes[1,0].grid(True)
    axes[1,0].invert_yaxis()
    step = max(1, N // 20)
    L = 0.003

    # 3.1 We need to create a for loop because we need to show the trajectory
    # for each of the points along the path since and we know that it's 0<=t<=20
    # so this loop is responsible for making sure that it is included in the graph

    for i in range(0, N, step):
        a  = np.cos(d['theta'][i])
        b  = np.sin(d['theta'][i])
        px = d['x'][i]
        pz = d['z'][i]
        axes[1,0].annotate("",xy=(px+a*L, pz+b*L), xytext=(px, pz),
            arrowprops=dict(arrowstyle="-|>", color='black', lw=1.0))
        axes[1,0].annotate("",xy=(px-b*L, pz+a*L), xytext=(px, pz),
            arrowprops=dict(arrowstyle="-|>", color='black', lw=1.0))

# 4. Creating a plot of the body-frame accelerometer components versus time
# in this one we are using the variables that we have found before, which are the
# functions fx_b and fz_b since we in the 2-D space we are plotting in the x- and
# the z-axis
    axes[1,1].plot(d['t'], d['fx_b'], label='fx_b')
    axes[1,1].plot(d['t'], d['fz_b'], label='fz_b')
    axes[1,1].set(title="Body-frame accelerometer components versus", xlabel="time [s]", ylabel="[m/s^2]")
    axes[1,1].grid(True)
    axes[1,1].legend()

    plt.savefig("imu2dplots.png", dpi=150, bbox_inches="tight")

# ** NOTE: there is some noise in the subplot with the visualization of the IMU
# motion in the plane and currently working on making sure that the noise will
# not be seen on the graph using the NOTCH FILTER, which I am going to implement

d2 = simulate_2d()
plot_2d(d2)

# -- 5. Plotting in the 3d space --------------------


# 1. Creating the overall figure that we are going to be adding the subplots to
def plot_3d(d):
    fig = plt.figure(figsize=(10, 5))
    fig.suptitle("3D IMU Simulation Extension plot", fontsize=10)

# 2. Creating the first subplot, which is going to be plotting the IMU trajectory
# but this time we are doing it in a 3D space, so we are also implementing the y
# coordinate
    ax1 = fig.add_subplot(1, 2, 1, projection='3d')
    ax1.plot(d['x'], d['y'], d['z'])
    ax1.set(title="3D IMU trajectory: position",
            xlabel="x [m]", ylabel="y [m]", zlabel="z [m]")

# 3. Now we can create a subplot that will find and plot the ideal body-frame accelerometer
# measurement over time
    ax2 = fig.add_subplot(2, 2, 2)
    ax2.plot(d['t'], d['fx_b'], label='fx_b')
    ax2.plot(d['t'], d['fy_b'], label='fy_b')
    ax2.plot(d['t'], d['fz_b'], label='fz_b')
    ax2.set(title="An ideal body-frame accelerometer measurement over time", xlabel="time [s]", ylabel="[m/s^2]")
    ax2.grid(True)
    ax2.legend()

# 4. Finding the Angular velocity and the orientation
# We neeed to include our 3x3 array which was already defined before hand
    ax3 = fig.add_subplot(2, 2, 4)
    ax3.plot(d['t'], d['wx'], label='wx')
    ax3.plot(d['t'], d['wy'], label='wy')
    ax3.plot(d['t'], d['wz'], label='wz')
    ax3.set(title="Angular Velocity", xlabel="time [s]", ylabel="[rad/s]")
    ax3.grid(True)
    ax3.legend()

    plt.subplots_adjust(hspace=0.4, wspace=0.5)  # ← add here
    plt.savefig("imu3dplots.png", dpi=150, bbox_inches="tight")
    plt.show()


d3 = simulate_3d()
plot_3d(d3)